//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Emisor
{
    public int EMI_CODIGO { get; set; }
    public string EMI_DESCRIPCION { get; set; }
    public string EMI_PREFIJO { get; set; }
    public int EMI_NUMERO_DIGITOS { get; set; }
}

public partial class Tarjeta
{
    public int TAR_CODIGO { get; set; }
    public string TAR_NUMERO { get; set; }
    public string TAR_TIPO { get; set; }
    public decimal TAR_SALDO { get; set; }
    public System.DateTime TAR_FECHA_EMISION { get; set; }
    public System.DateTime TAR_FECHA_VENCIMIENTO { get; set; }
    public string TAR_ESTADO { get; set; }
    public int TAR_CODIGO_CLIENTE { get; set; }
    public string TAR_NOMBRE_CLIENTE { get; set; }
}
