//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioTarjetas
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Emisor", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Emisor : object
    {
        
        private int EMI_CODIGOField;
        
        private string EMI_DESCRIPCIONField;
        
        private int EMI_NUMERO_DIGITOSField;
        
        private string EMI_PREFIJOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMI_CODIGO
        {
            get
            {
                return this.EMI_CODIGOField;
            }
            set
            {
                this.EMI_CODIGOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMI_DESCRIPCION
        {
            get
            {
                return this.EMI_DESCRIPCIONField;
            }
            set
            {
                this.EMI_DESCRIPCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMI_NUMERO_DIGITOS
        {
            get
            {
                return this.EMI_NUMERO_DIGITOSField;
            }
            set
            {
                this.EMI_NUMERO_DIGITOSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMI_PREFIJO
        {
            get
            {
                return this.EMI_PREFIJOField;
            }
            set
            {
                this.EMI_PREFIJOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioTarjetas.IServicioTarjetas")]
    public interface IServicioTarjetas
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTarjetas/GetData", ReplyAction="http://tempuri.org/IServicioTarjetas/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTarjetas/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServicioTarjetas/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServicioTarjetas.CompositeType> GetDataUsingDataContractAsync(ServicioTarjetas.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTarjetas/ObtenerEmisores", ReplyAction="http://tempuri.org/IServicioTarjetas/ObtenerEmisoresResponse")]
        System.Threading.Tasks.Task<ServicioTarjetas.Emisor[]> ObtenerEmisoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTarjetas/ObtenerEmisoresPorNombre", ReplyAction="http://tempuri.org/IServicioTarjetas/ObtenerEmisoresPorNombreResponse")]
        System.Threading.Tasks.Task<ServicioTarjetas.Emisor[]> ObtenerEmisoresPorNombreAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicioTarjetasChannel : ServicioTarjetas.IServicioTarjetas, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioTarjetasClient : System.ServiceModel.ClientBase<ServicioTarjetas.IServicioTarjetas>, ServicioTarjetas.IServicioTarjetas
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioTarjetasClient() : 
                base(ServicioTarjetasClient.GetDefaultBinding(), ServicioTarjetasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioTarjetas.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTarjetasClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioTarjetasClient.GetBindingForEndpoint(endpointConfiguration), ServicioTarjetasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTarjetasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioTarjetasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTarjetasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioTarjetasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTarjetasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<ServicioTarjetas.CompositeType> GetDataUsingDataContractAsync(ServicioTarjetas.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Threading.Tasks.Task<ServicioTarjetas.Emisor[]> ObtenerEmisoresAsync()
        {
            return base.Channel.ObtenerEmisoresAsync();
        }
        
        public System.Threading.Tasks.Task<ServicioTarjetas.Emisor[]> ObtenerEmisoresPorNombreAsync(string nombre)
        {
            return base.Channel.ObtenerEmisoresPorNombreAsync(nombre);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioTarjetas))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioTarjetas))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59736/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioTarjetasClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioTarjetas);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioTarjetasClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioTarjetas);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioTarjetas,
        }
    }
}
